[package]
name = "kani"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-sdk = "0.43.0"
clap = { version = "4.4.7", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
nostr = { version = "0.43.0", features = ["nip06", "nip04", "nip46", "nip03"] }
