[package]
name = "nostr-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-sdk = "0.30.0"
clap = { version = "4.4.7", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
nostr = { version = "0.30.0", features = ["nip06"] }
